"""create schema tables and initial data.

Revision ID: ea16216081d6
Revises: 
Create Date: 2023-05-07 23:50:37.061902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea16216081d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_balance', sa.Float(), nullable=False),
    sa.Column('operation_response', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create initial data
    op.execute("INSERT INTO users (username, password) VALUES ('danielssj88', PASSWORD('12345678'))")
    op.execute("INSERT INTO users (username, password) VALUES ('test.trueNorth', PASSWORD('Daniel123'))")

    op.execute("INSERT INTO operations (type, cost) VALUES ('addition', 10.0)")
    op.execute("INSERT INTO operations (type, cost) VALUES ('substraction', 10.0)")
    op.execute("INSERT INTO operations (type, cost) VALUES ('multiplication', 15.0)")
    op.execute("INSERT INTO operations (type, cost) VALUES ('division', 20.0)")
    op.execute("INSERT INTO operations (type, cost) VALUES ('square_root', 25.0)")
    op.execute("INSERT INTO operations (type, cost) VALUES ('random_string', 5.0)")


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('users')
    op.drop_table('operations')
    # ### end Alembic commands ###
